CREATE TABLE user_posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    content TEXT,
    title TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY(user_name) REFERENCES journal_users(user_name) ON DELETE CASCADE 

);



  