
const { json } = require('express');
const express = require('express')
const bodyParser = express.json()
const JournalRouter = express.Router()
const { JournalService } = require('../service-objects/journal-service')
const app = express();
const xss = require('xss')

const serializePosts = post => ({  
    id: post.id,
    title : xss(post.title),
    content : xss(post.content),
    modified: post.modified,    
})



JournalRouter
    .route('/:user-name/:id')
    .all((req,res,next) => {
        JournalService.getPost(
            req.app.get('db'),
            req.params.id,
            req.params.user-name
        )
        .then(post => {
            if(!post) {
                return res.status(404).json(
                {error:
                    {message : `Post not found`}
                 }
                )
            }
            res.post = post 
            next();
        })
        .catch(next);
    })
    .get((req,res,next) => {
        res.json(res.post)
    })
    .delete((req,res,next) => {
        JournalService.deletePost(
            req.app.get('db'),
            req.params.id
        )
        .then(post => {
            return res.status(204).end();
        })
        .catch(next);

    })
    .patch(bodyParser,(req,res,next) => {

        //cannot update title only content
        const { content } = req.body
        const updatedContent  = { content }

        const numOfValues = Object.values(updatedContent).filter(Boolean).length

        if(numOfValues == 0){
            return res.status(400).json({error:
            {message : `Req.body must contain updated content`}})
        }

        JournalService.updatePost(
            req.get.app('db'),
            req.params.id,
            updatedContent
        )
        .then(updatedContent => {
            return res.status(204).end()
        })
        .catch(next);       
    })


    JournalRouter   
        .route('/:user-name')
        .post(bodyParser, (req,res,next) => {
            
            //do i need to include modified in here? I belive
            //it should be autogenerated for me:
           const { title, content } = req.body
           const newPost = { title, content }


           for (const[value] of Object.entries(newPost)){
               if(value == null){
                   //204 instead of 400?
                   return res.status(400).json({error:
                {message:`Nothing to Post`}});
               }
           }

           JournalService.createPost(
               req.get.app('db'),
               newPost 
           )
           .then( post => {
                res
                    .status(201)
                    .location(path.posix.join(req.originalUrl),`/${post.id}`)
                    .json(serializePosts(post))
           })
           .catch(next);
        });


module.exports = JournalRouter;

